### ISSUE TITLE
servo_power_monitor:  TODO list

### ISSUE THREAD

**Issue by wtrgjadmw** [google/lium#139]
- [ ] Add annotation in graph
- [ ] Automation of workload running & stopping the measurement
- [ ] Change from "Stop" button to "Cancel" button: cancel measurement & workload
- [ ] Enable customization of workload & config shell script
- [ ] Extract the power data except for margin part & draw histogram based on it
- [ ] Run 2 configs measurement
- [ ] Run multiple iterations & customization of iteration number
- [ ] draw histogram & box plot in real time for each iteration
- [ ] Create a selector for iteration which is corresponding to objective graph

**Comment by wtrgjadmw** [comment]
If I have time:

- [ ] add highlight between the annotations in the power graph
